### ISSUE TITLE
Tutorial - Error when click Save at Edit

### ISSUE THREAD

**Issue by CCH4GITHUB** [geddy/geddy#725] opened 2017-02-13 12:01 UTC
Edit, Click Save gives rise to this error message

Error: 500 Internal Server Error
Error
    at createConstructor (C:\Users\User\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:68:34)
    at new <anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:79:33)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:21:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by ckhatton** [comment] 2017-02-19 10:19
Are you using node "~> 5.12.0"?

**Comment by CCH4GITHUB** [comment] 2017-02-20 13:25
Hi Chris

Latest LTS Version: v6.9.5 (includes npm 3.10.10)

**Comment by ckhatton** [comment] 2017-02-20 16:12
What's LTS? :confused:

The node version cannot be any higher than v5 for Geddy to function. :octopus:

**Comment by ckhatton** [comment] 2017-02-20 16:36
I get what you mean now, the node version has to be v5. You can use 'nvm' if you want to manage the versions.

**Comment by ckhatton** [comment] 2017-02-22 09:59
@CCH4GITHUB Can I close this now? 🚪

**Comment by mde** [comment] 2017-02-25 19:51
@ckhatton, did we open a ticket for getting Ged working on the newest Nodes?

**Comment by ckhatton** [comment] 2017-02-25 21:16
I don't believe one has been created.

Can I possibly have a higher level of access? I would like to go through the issues and label them 'bug', 'feature', etc.

**Comment by mde** [comment] 2017-02-25 23:39
Done!

**Comment by ckhatton** [comment] 2017-02-26 00:09
Actually, doesn't look like it worked...

**Comment by mde** [comment] 2017-02-26 00:10
Look for an invitation to the group in e-mail.

**Comment by ckhatton** [comment] 2017-02-26 13:35
I still haven't received the email :( I have checked my spam folder as well.

**Comment by mde** [comment] 2017-02-28 16:56
Ugh. Can you look in your GitHub notifications to see if it's there? Maybe your notifications don't go to e-mail?

**Comment by mde** [comment] 2017-03-04 18:33
@ckhatton Is this the same error you saw trying to use Ged with the latest Node?

**Comment by mde** [comment] 2017-03-04 19:11
Looks like the breakage was caused by https://github.com/nodejs/node/pull/6289, changing the querystring module to use null-proto objects. Fixed in mde/utilities@c906146de2eb1bb0ab603e46a0d9edddca538b3d Update your deps, and things should work. Let me know if there's more breakage.

**Closed by mde** 2017-03-04 19:11 UTC

**Comment by ckhatton** [comment] 2017-03-06 13:14
Thinking about it, I think it was haha. An error would occur when saving a database record - So it does sound the same.

I kinda get the solution haha. Out of interest, how does Geddy link to the utilities repo? Do you have a asset call link to the raw source file in the utilities repo?

I have just tested the Geddy tutorial using Node v6, and it is working fine :smiley::+1:

> **P.S:**
> I have noticed the page assets load in slower using Node v6. The background is white for a second, until the grey texture has loaded into the DOM. :confused:

**Comment by mde** [comment] 2017-03-06 17:20
Geddy just uses the `utilities` lib as a standard CommonJS `require`. You can see all the stuff it uses in the package.json.

I haven't noticed any specific speed difference with Node 6, but in production, you probably wouldn't want to be serving the static assets with Node anyhow. You'd front your app with something like Ngnix to serve those.

**Comment by ckhatton** [comment] 2017-03-13 22:51
> Geddy just uses the `utilities` lib as a standard CommonJS `require`.

Oh yeah, of course!
